### PR TITLE
Removed redundant methods, comments and fixed methods with > 30 LOC

### LINKED ISSUE #157: Fix methods that are too long
Methods must be at most 30 LOC

### LINKED ISSUE #160: Remove unnecessary comments
remove unnecessary comments like this

Image

### LINKED ISSUE #161: Rename DeleteCommandParserTest to DeleteStudentCommandParserTest

### LINKED ISSUE #162: Remove redundant variables and methods
Remove redundant variables like this one

Image

### PR DESCRIPTION
**Pull request by waylonggggg**
Fixes #157 
Fixes #160 
Fixes #161
Fixes #162

**After merging, make sure you delete addressbook.json and reload again. I removed a redundant totalsessions attribute that was present in jsonadaptedccainformation**

Renamed deletecommandparsertest to deletestudentcommandparsertest
Fixed most methods with > 30 LOC, removed redundant methods and removed redundant comments.
Methods in Addressbookparser, editstudentcommandparser and jsonadaptedperson method is > 30 LOC, but so was the original. Should we fix it?
JsonAdaptedRole.getRoleName() is unused, but in the original AB3 it was originally getTagName() but also unused. Remove?

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCcaToStudentCommand.java [hunk 1]
```diff
@@ -39,89 +37,53 @@ public class AddCcaToStudentCommand extends Command {
...
         if (personToAddCca.hasCca(targetCca)) {
             throw new CommandException(MESSAGE_CCA_ALREADY_PRESENT);
         }
 
-        CcaInformation newCcaInfo = new CcaInformation(targetCca,
-                Role.DEFAULT_ROLE,
-                targetCca.createNewAttendance());
-
+        CcaInformation newCcaInfo = new CcaInformation(targetCca, Role.DEFAULT_ROLE, targetCca.createNewAttendance());
         Set<CcaInformation> updatedCcaInformations = new HashSet<>(personToAddCca.getCcaInformations());
```
Comment (Judy1x4) [inline src/main/java/seedu/address/logic/commands/AddCcaToStudentCommand.java:76]: im not sure what is this updated Ccainformation for? perhaps can remove it

File: src/main/java/seedu/address/logic/commands/AddCcaToStudentCommand.java [hunk 2]
```diff
@@ -39,89 +37,53 @@ public class AddCcaToStudentCommand extends Command {
...
-        assert personWithAddedCca != null : "Newly created Person object should not be null.";
-        assert personWithAddedCca.hasCca(targetCca) : "Newly created Person should have the target CCA.";
-
         model.setPerson(personToAddCca, personWithAddedCca);
-
         model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
-        return new CommandResult(String.format(MESSAGE_ADD_CCA_SUCCESS,
-                Messages.format(personWithAddedCca),
+        return new CommandResult(String.format(MESSAGE_ADD_CCA_SUCCESS, Messages.format(personWithAddedCca),
                 Messages.format(ccaName)));
```
Comment (Judy1x4) [inline src/main/java/seedu/address/logic/commands/AddCcaToStudentCommand.java:84]: I think can remove the ccaName (because that is how it is done in other commands as well). I've pointed out this in the last @Nova1729 's PR, but he may have missed it out.

File: src/main/java/seedu/address/model/cca/CcaName.java [hunk 3]
```diff
@@ -13,12 +13,6 @@ public class CcaName {
             "Cca names must start with a letter, must not be empty or purely numeric, "
                     + "and can contain alphanumeric characters, whitespace and hyphens only."
                     + "Multiple words are allowed, but only one whitespace or hyphen is allowed between words.";
-
-    /*
-     * The string must start with a letter.
```
Comment (Judy1x4) [inline src/main/java/seedu/address/model/cca/CcaName.java:18]: I think better not remove this (cos in the originial AB3 also had this in the validation regex)

**Review by Judy1x4 — APPROVED** [review]
LGTM (the code does get rid of 30 LoC)
