### PR TITLE
Fix unchecked exception

### LINKED ISSUE #119: Adjust recordAttendance method in Model command
The current model has `recordAttendance` method, which may be considered not adhering to Separation of Concern and Single Responsibility Principle. Instead, the logic should be handled in execute() of RecordAttendanceCommand.

### PR DESCRIPTION
**Pull request by thegrimbee**
Fixes #119 
#121 

Made a public method isValidPersonCcas for commands to use to throw the appropriate message when a person's cca is not valid

I didn't change editStudentCommand since we're going to change it to no longer handle CCAs

### CODE REVIEW

File: src/main/java/seedu/address/model/AddressBook.java [hunk 1]
```diff
@@ -47,14 +47,28 @@ public AddressBook(ReadOnlyAddressBook toBeCopied) {
...
+    }
+
+    /**
+     * Validates that all CCAs in the given {@code person} exist in the UniqueCcaList.
+     *
+     * @throws IllegalArgumentException if any CCA in the person does not exist in the UniqueCcaList.
+     */
+    private void validatePersonCcas(Person person) throws IllegalArgumentException {
+        if (!isValidPersonCcas(person)) {
+            throw new IllegalArgumentException(MESSAGE_CCA_NOT_FOUND);
```
Comment (Judy1x4) [inline src/main/java/seedu/address/model/AddressBook.java:70]: seems good

File: src/main/java/seedu/address/logic/commands/RecordAttendanceCommand.java [hunk 2]
```diff
@@ -61,17 +59,13 @@ public CommandResult execute(Model model) throws CommandException {
...
-        }
-        try {
-            model.recordAttendance(ccaName, student, amount);
-            Name studentName = student.getName();
-            return new CommandResult(String.format(MESSAGE_SUCCESS, Messages.format(studentName),
-                    Messages.format(ccaName), Messages.format(amount)));
-        } catch (CcaNotFoundException e) {
-            throw new CommandException(Messages.MESSAGE_CCA_NOT_FOUND);
-        } catch (IllegalArgumentException e) {
+        } else if (!student.canAttend(ccaName, amount)) {
```
Comment (Judy1x4) [inline src/main/java/seedu/address/logic/commands/RecordAttendanceCommand.java:62]: later when getCca is implemented, perhaps its better to pass Cca object in `student.canAttend` method, which then we can get rid of one of the `getCcaInformation` in Person class.

```
    // TODO: Remove this method after record attendance method in model is removed.
    /**
     * Returns the CCA information associated with the specified CCA.
     *
     * @param ccaName The CCA name to retrieve information for.
     * @return The {@code CcaInformation} object associated with the specified CCA.
     */
    public CcaInformation getCcaInformation(CcaName ccaName) throws CcaNotFoundException {
        for (CcaInformation ccaInformation : ccaInformations) {
            if (ccaInformation.getCca().getCcaName().equals(ccaName)) {
                return ccaInformation;
            }
        }
        throw new CcaNotFoundException();
    }

    /**
     * Returns the CCA information associated with the specified CCA.
     * {@code cca} must exist in the person's CCA information.
     *
     * @param cca The CCA to retrieve information for.
     * @return The {@code CcaInformation} object associated with the specified CCA.
     * @throws CcaNotFoundException If the specified CCA is not found in the person's CCA information.
     */
    public CcaInformation getCcaInformation(Cca cca) {
        for (CcaInformation ccaInformation : ccaInformations) {
            if (ccaInformation.getCca().equals(cca)) {
                return ccaInformation;
            }
        }
        throw new CcaNotFoundException();
    }
```

**Review by Judy1x4 — COMMENTED** [review]
LGTM

**Review by Judy1x4 — APPROVED** [review]
